mqtt:
  enabled: True
  host: raspberrypi.local

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  front-door:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://<user>:<password>@192.168.86.38:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
      hwaccel_args: preset-rpi-64-h264
    detect:
      enabled: True
      width: 1920
      height: 1080
    snapshots:
      enabled: True
    record:
      enabled: True

