version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/gabriel/ha/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  mosquito:
    container_name: mqtt
    image: eclipse-mosquitto
    volumes:
      - /home/gabriel/mosquitto/config:/mosquitto/config
      - /home/gabriel/mosquitto/data:/mosquitto/data
      - /home/gabriel/mosquitto/log:/mosquitto/log
    network_mode: host
  double-take:
    container_name: double-take
    image: skrashevich/double-take
    restart: unless-stopped
    volumes:
      - /home/gabriel/double-take/storage:/.storage
    ports:
      - 3000:3000
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/video10
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/gabriel/frigate/config/config.yml:/config/config.yml:ro
      - /home/gariel/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
